### ISSUE TITLE
Problem on OpenApi when param is not named exactly "filter"

### ISSUE THREAD

**Issue by StyloNemesis** [acoboh/query-filter-jpa#28]
**Description**
There is a problem with OpenApi when you name your QFParam with other name different than "filter" when the documentation is not displayed as expected in Swagger. 
It only works well when the `@RequestParam` is exactly named "filter".

**QueryFilter Version**
0.1.0

**Spring Boot Version**
3.2.0 (Same problem using 3.1.4)

**Screenshots**
`@Parameter(description = "Filters") @QFParam(SocialNetworkFilterDef.class) @RequestParam(value = "filters", required = false) QueryFilter<SocialNetwork> filters`
![image](https://github.com/acoboh/query-filter-jpa/assets/106996499/6302ff94-56fe-4b00-bcfe-766fba212b1e)

`@Parameter(description = "Filter") @QFParam(SocialNetworkFilterDef.class) @RequestParam(value = "filter", required = false) QueryFilter<SocialNetwork> filter`
![image](https://github.com/acoboh/query-filter-jpa/assets/106996499/c8290072-32cf-4d97-a507-b5ae31f28735)

**Comment by acoboh** [comment]
It will be solved on the next release 0.2.0
