### ISSUE TITLE
Sort alone is not working when predicate is set

### ISSUE THREAD

**Issue by StyloNemesis** [acoboh/query-filter-jpa#31]
**Description**
There is a problem when you have a QueryFilter definition with a predicate and you add that predicate in code at runtime.
When you have this, you can filter and filter & order at the same time, but if you try to only order by one of the fields the return is always empty.

**QueryFilter Version**
0.1.0

**Spring Boot Version**
3.2.0 

**Query executed by JPA**
`name=eq:test&sort=-name`

```
select
        distinct et1_0.id,
        et1_0.name
        et1_0.type
    from
        schema.entity_test et1_0 
    where
        et1_0.name=? 
    order by
        et1_0.name desc 
    offset
        ? rows 
    fetch
        first ? rows only
```

`sort=-name`

```
    select
        distinct et1_0.id,
        et1_0.name
        et1_0.type 
    from
        schema.entity_test et1_0 
    where
        1!=1 
    order by
        et1_0.name desc 
    offset
        ? rows 
    fetch
        first ? rows only
```

**Comment by acoboh** [comment]
Will be fixed on next release 0.2.0
